### ISSUE TITLE
mtg_patch_023.tre 

### ISSUE THREAD

**Issue by Rushgunner1** [ModTheGalaxy/mtgserver#31]
Where is the direct DL for mtg_patch_023.tre ?

**Comment by lasko2112** [comment]
There is not one yet.

The tre is being worked on by multiple people and will be constantly changing.

The best option is to download it directly from the repo and build it in SIE. That way you will be gauranteed to have the latest version.

https://github.com/ModTheGalaxy/mtg_patch_023-tre
